/** Stable names for rows in `ride_events.type`. */
export const EventType = {
  RIDE_REQUESTED: 'RIDE_REQUESTED',
  REQUEST_MATCHED: 'REQUEST_MATCHED',
  REQUEST_STARTED: 'REQUEST_STARTED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
  REQUEST_CANCELLED: 'REQUEST_CANCELLED',
  REQUEST_REQUEUED: 'REQUEST_REQUEUED',
  POOL_CREATED: 'POOL_CREATED',
  PASSENGER_JOINED: 'PASSENGER_JOINED',
  PASSENGER_LEFT: 'PASSENGER_LEFT',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  POOL_STARTED: 'POOL_STARTED',
  POOL_COMPLETED: 'POOL_COMPLETED',
  POOL_CANCELLED: 'POOL_CANCELLED',
} as const;
export type EventType = (typeof EventType)[keyof typeof EventType];
